services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: shopping_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shopping_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_service
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shopping_network

  eureka-server:
    build: ./ms-eureka
    container_name: ms-eureka
    restart: always
    ports:
      - "8761:8761"
    networks:
      - shopping_network

  ms-users:
    build: ./ms-users
    container_name: ms-users
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_SERVER: http://ms-eureka/
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - shopping_network

volumes:
  postgres_data:

networks:
  shopping_network:
    driver: bridge
    name: shopping_network