server:
  port: 8081

spring:
  application:
    name: ms-users
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_db
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    jwt:
      secret-key: "17KlgIf}WM[H7TBunx/9M!bFyT2gUM@G"
      expiration-time: 3600000
      password-reset-expiration: 900000
  mail:
    host: smtp.gmail.com
    port: 587
    username: "murillo.murillo2001@gmail.com"
    password: "umad yauv aeku tphh"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ms-users
    prefer-ip-address: false