server:
  port: 8081

spring:
  application:
    name: ms-users
  datasource:
    url: jdbc:postgresql://postgres_db:5432/shopping_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ms-users
    prefer-ip-address: false